# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - 0.5
  - 0.6
  # - nightly
notifications:
  email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.test("ExpFamily"; coverage=true)'
after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("ExpFamily")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # - julia -e 'Pkg.add("Documenter"); cd(Pkg.dir("PDMP")); include(joinpath("docs", "make.jl"))'
